[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

# opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono NF"

size = 13

[general]
import = [
  "~/.config/alacritty/themes/coolnight.toml"
]

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[[mouse.bindings]]
mouse = "Right"
action = "Paste"

# [[keyboard.bindings]]
# key = "PageUp"
# mods = "Shift"
# action = "ScrollPageUp"
# mode = "~Alt"
# 
# [[keyboard.bindings]]
# key = "PageDown"
# mods = "Shift"
# action = "ScrollPageDown"
# mode = "~Alt"
# 
# [[keyboard.bindings]]
# key = "Home"
# mods = "Shift"
# action = "ScrollToTop"
# mode = "~Alt"
# 
# [[keyboard.bindings]]
# key = "End"
# mods = "Shift"
# action = "ScrollToBottom"
# mode = "~Alt"
